spring:
  application:
    # 应用名称
    name: watch-wrist
  main:
    allow-bean-definition-overriding: false
  profiles:
    # 环境配置
    active: dev
  datasource:
    name: druidDataSource

    url: jdbc:mysql://127.0.0.1:3306 #GMT
    #url: jdbc:mysql://localhost:3306/breathing_cloud_device?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC #GMT
    username:
    #password: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #redis:
    # host : 39.105.157.251
    # host : 127.0.0.1
    # port : 6379
    # password : yian@123
      # jedis:
      #   pool:
      #    max-active: 8  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      #    max-wait: -1   # 连接池中的最大空闲连接
      #    min-idle: 0    # 连接池中的最小空闲连接
      #    timeout: 100000  # 连接超时时间（毫秒）
      #cloud:
      # nacos:
      #discovery:
      # 服务注册地址
      #server-addr: 39.107.124.52:8848
      #config:
      # 配置中心地址
      #server-addr: 39.107.124.52:8848
      # 配置文件格式
      #file-extension: yml
      # 共享配置
    #shared-configs: application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
mybatis:
  type-aliases-package: com.yian.breathing.model
  mapper-locations: classpath*:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml
logging:
  level:
    com.yian.breathing: INFO
    com.yian.dao: debug
    jdbc.sqltiming: debug
    org.springframework : Warn
    reactor:
      ipc:
        netty: DEBUG
  config: classpath:logback-spring.xml
jks:
  path: D:\\test.jks
  password: 123456

